<Project>
	<!-- 👇 静态本机编译 & 剪裁 | AOT & Trimmable -->
	<PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">
		<IsTrimmable>true</IsTrimmable>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

</Project>
